/**
 * The full six-week full stack interview syllabus.
 *
 * Each item is encoded as "week|priority|title|question" to keep the file
 * readable and small. Priority is M (core), S (likely) or E (senior).
 */

export type Priority = "M" | "S" | "E";

export type SyllabusItem = {
  week: number;
  priority: Priority;
  title: string;
  question: string;
};

export type SyllabusGroup = {
  name: string;
  items: SyllabusItem[];
};

export type SyllabusTrack = {
  number: string;
  id: string;
  name: string;
  blurb: string;
  groups: SyllabusGroup[];
};

export const priorityLabels: Record<Priority, string> = {
  M: "Core",
  S: "Likely",
  E: "Senior",
};

export const weeks: { label: string; focus: string }[] = [
  { label: "Week 01", focus: "JavaScript and TypeScript deep dive, DSA foundations, resume rebuilt" },
  { label: "Week 02", focus: "React, the browser and CSS, lists and stacks — start applying" },
  { label: "Week 03", focus: "Node, Express, auth, low level design and patterns, trees" },
  { label: "Week 04", focus: "Postgres, MongoDB, Redis, SQL by hand, graphs and heaps" },
  { label: "Week 05", focus: "System design, DevOps and cloud, dynamic programming and binary search" },
  { label: "Week 06", focus: "React Native, testing, CS fundamentals, behavioural rounds, mock interviews" },
];

type RawTrack = {
  number: string;
  id: string;
  name: string;
  blurb: string;
  groups: [string, string[]][];
};

const raw: RawTrack[] = [
  {
    number: "01",
    id: "js",
    name: "JavaScript & TypeScript",
    blurb:
      "The single highest-yield track. Every round — frontend, backend, machine coding — is conducted in this language, and interviewers probe it harder than anything else on your resume.",
    groups: [
      [
        "Language fundamentals",
        [
          "1|M|var, let, const and the temporal dead zone|Why does reading a `let` before its declaration throw, while `var` gives undefined?",
          "1|M|Hoisting — variables, functions, classes|What exactly gets hoisted, and what does not?",
          "1|M|Primitives vs reference types|Is JavaScript pass-by-value or pass-by-reference? Defend your answer.",
          "1|M|Type coercion, == vs ===, truthy and falsy|Predict the output: `[] == false`, `null == undefined`, `NaN == NaN`",
          "1|M|typeof, instanceof, Array.isArray, Object.prototype.toString|Why is `typeof null` object, and how do you reliably detect an array?",
          "1|M|Destructuring — object, array, nested, defaults, rest|Swap two variables without a temp; pull a nested value with a default.",
          "1|M|Spread vs rest; shallow vs deep copy|Why does spreading a nested object still share references?",
          "1|M|Optional chaining, nullish coalescing, logical assignment|When does `??` behave differently from a plain OR?",
          "1|S|Template literals and tagged templates|",
          "1|S|Strict mode — what it actually changes|",
          "1|S|Number precision, 0.1 + 0.2, Number.EPSILON, BigInt|Why is `0.1 + 0.2 !== 0.3` and how do you compare floats safely?",
          "1|S|JSON.stringify and parse — replacer, reviver, what is lost|What happens to undefined, functions, Symbols and circular refs?",
          "1|E|Symbols and well-known symbols|What does `Symbol.iterator` let you do?",
          "1|E|Labeled statements, switch fallthrough, comma operator|",
        ],
      ],
      [
        "Scope, closures and this",
        [
          "1|M|Lexical scope and the scope chain|",
          "1|M|Closures — definition, uses, memory cost|Explain a closure to someone who has never heard the word.",
          "1|M|The classic loop + setTimeout puzzle|Why does a `var` loop print 3,3,3 and `let` print 0,1,2? Fix it three ways.",
          "1|M|this — default, implicit, explicit, new, arrow binding|What is `this` inside a method passed as a callback, and how do you fix it?",
          "1|M|call, apply, bind — and implement your own bind|Write `Function.prototype.myBind` supporting partial application.",
          "1|M|Arrow functions vs regular functions|Name four concrete differences. When must you NOT use an arrow?",
          "1|M|Practical closures: once, memoize, counter, private state|Implement `memoize(fn)` with a cache key strategy.",
          "1|S|Currying and partial application|Implement `curry(fn)` and infinite currying `sum(1)(2)(3)()`.",
          "1|S|IIFE and the module pattern|",
          "1|E|Function composition and pipe|Implement `pipe(...fns)` and `compose(...fns)`.",
        ],
      ],
      [
        "Objects, prototypes and classes",
        [
          "1|M|The prototype chain; __proto__ vs prototype|How does property lookup actually resolve?",
          "1|M|Constructor functions and new — implement myNew|Write a function that replicates what `new` does, step by step.",
          "1|M|ES6 classes, extends, super, static, private #fields|Are classes just syntactic sugar? What is genuinely new?",
          "1|M|Prototypal vs classical inheritance|",
          "1|M|Object.create, getPrototypeOf, setPrototypeOf|",
          "1|S|Property descriptors and Object.defineProperty|What do writable, enumerable and configurable control?",
          "1|S|Object.freeze, seal, preventExtensions; deep freeze|Write `deepFreeze(obj)`.",
          "1|S|Getters, setters and computed properties|",
          "1|S|Object statics: keys, values, entries, assign, fromEntries, groupBy|",
          "1|E|Mixins and composition over inheritance|",
          "1|E|Proxy and Reflect|How would you build an observable object with a Proxy?",
        ],
      ],
      [
        "Arrays, iteration and collections",
        [
          "1|M|Every array method and its return value|map vs forEach vs filter vs reduce — when does each one belong?",
          "1|M|Implement your own map, filter, reduce, forEach|Write `Array.prototype.myReduce` handling the no-initial-value case.",
          "1|M|reduce in anger: groupBy, flatten, frequency map, pipe|Group an array of objects by a key using only reduce.",
          "1|M|sort — default lexicographic behaviour, comparators, stability|Why does `[10,9,1].sort()` give 1,10,9?",
          "1|M|Map and Set — and why not just use an object|When is a Map strictly better than a plain object?",
          "1|S|WeakMap and WeakSet|Why would you cache with a WeakMap instead of a Map?",
          "1|S|flat, flatMap; implement your own flatten with depth|",
          "1|S|Array-likes vs iterables; arguments; Array.from|",
          "1|S|Iterators and the iterable protocol|Make a plain object iterable with `for...of`.",
          "1|E|Generators and yield; infinite sequences; async generators|",
          "1|E|Typed arrays and ArrayBuffer|",
        ],
      ],
      [
        "Asynchronous JavaScript",
        [
          "1|M|Sync vs async, blocking vs non-blocking|",
          "1|M|Callbacks, callback hell, error-first convention|",
          "1|M|Promises — states, then/catch/finally, chaining rules|What does returning a value vs a promise inside `.then` do?",
          "1|M|Promise.all vs allSettled vs race vs any|You fire five API calls and one may fail. Which do you use and why?",
          "1|M|async/await, try/catch, for await...of|",
          "1|M|Sequential vs parallel awaits — the classic perf bug|Spot why awaiting inside a loop made an endpoint 10x slower.",
          "1|M|The event loop: call stack, task queue, microtask queue|Predict the output order of setTimeout, Promise.then and sync logs.",
          "1|M|Microtasks vs macrotasks|Why does a Promise callback beat a setTimeout(0)?",
          "1|M|Debounce and throttle — implement both|Write debounce with leading and trailing edge options. Where would you use each?",
          "1|M|Implement your own Promise (then, catch, resolve, reject)|A senior-round favourite. Build it from scratch.",
          "1|M|Implement Promise.all and Promise.allSettled polyfills|",
          "1|M|Retry with exponential backoff|Write `retry(fn, attempts, baseDelay)` with jitter.",
          "1|M|Concurrency control — limit N parallel promises|Implement a promise pool that runs at most 3 requests at a time.",
          "1|S|promisify; converting a callback API to promises|",
          "1|S|AbortController — cancelling fetch, timeouts, cleanup|",
          "1|S|setTimeout(fn,0), setInterval drift, requestAnimationFrame, requestIdleCallback|",
          "1|S|Race conditions in async UI code|Two searches fire, the slow one lands last. How do you fix it?",
          "1|E|Async iterators and streaming responses|",
        ],
      ],
      [
        "Modules, tooling and the ecosystem",
        [
          "1|M|CommonJS vs ES modules|Differences in loading, hoisting, live bindings and circular dependencies.",
          "1|M|Dynamic import and top-level await|",
          "1|M|npm vs yarn vs pnpm; lockfiles; npm ci vs npm install|Why does a lockfile matter, and what breaks without one?",
          "1|M|Semver, caret vs tilde ranges, peer and dev dependencies|",
          "1|S|Bundlers: Webpack vs Vite vs esbuild vs Rollup|Why is Vite fast in dev, and what changes in a production build?",
          "1|S|Tree shaking, side effects, package.json exports and module fields|",
          "1|S|Babel, transpiling vs polyfilling, core-js, browserslist|",
          "1|S|Source maps — how and why|",
          "1|E|Monorepos: workspaces, Turborepo, Nx|",
          "1|E|Publishing a package; dual CJS/ESM builds|",
        ],
      ],
      [
        "Memory, gotchas and puzzles",
        [
          "1|M|Garbage collection and mark-and-sweep|",
          "1|M|Memory leaks in JS: closures, listeners, timers, detached DOM|How would you find a leak in a long-running SPA?",
          "1|M|Deep clone — handle nested objects, arrays, Date, Map, Set, cycles|Write it without structuredClone, then mention structuredClone.",
          "1|M|Deep equal — implement it|",
          "1|M|Event bubbling, capturing, delegation|stopPropagation vs preventDefault vs stopImmediatePropagation.",
          "1|S|Output-prediction puzzles combining hoisting, closures and the event loop|Do 20 of these. They open a huge share of screening rounds.",
          "1|S|Regex: groups, lookahead, greedy vs lazy, flags|Validate an email, extract all matches with groups.",
          "1|S|Dates, timezones, and why teams reach for date-fns or dayjs|Why is storing timestamptz in UTC the safe default?",
          "1|E|Intl for numbers, currency, dates and relative time|",
          "1|E|The Temporal API|",
        ],
      ],
      [
        "TypeScript",
        [
          "1|M|Why TypeScript; structural vs nominal typing|",
          "1|M|any vs unknown vs never vs void|When must you use unknown instead of any?",
          "1|M|Interfaces vs type aliases|Which do you reach for, and when does the difference actually matter?",
          "1|M|Union and intersection types, literal types, discriminated unions|Model an API response that is either success or error, exhaustively.",
          "1|M|Generics — functions, interfaces, classes, constraints, defaults|Write a generic `pick<T, K extends keyof T>`.",
          "1|M|Utility types: Partial, Required, Pick, Omit, Record, Exclude, Extract, ReturnType, Awaited|",
          "1|M|Type narrowing, type guards and `is` predicates|",
          "1|M|Exhaustiveness checking with never|How do you make the compiler fail when a new union member is added?",
          "1|M|Typing React: props, children, events, hooks, generic components|",
          "1|M|Typing Express: req, res, middleware, custom request properties|How do you add `req.user` in a type-safe way?",
          "1|S|keyof, typeof, indexed access types, as const|",
          "1|S|Enums vs const objects vs union of literals|Why do many teams avoid TS enums?",
          "1|S|tsconfig essentials: strict, strictNullChecks, target, module, paths|",
          "1|E|Conditional types and infer|",
          "1|E|Mapped types and template literal types|Build a type that turns every key into an onXChange handler.",
          "1|E|Declaration merging, module augmentation, .d.ts files|",
        ],
      ],
    ],
  },
  {
    number: "02",
    id: "react",
    name: "React & Frontend",
    blurb:
      "Interviewers assume anyone can wire up useState. What separates a 3-year candidate is knowing why a component re-rendered, when memoisation is useless, and how the browser turned your JSX into pixels.",
    groups: [
      [
        "React core",
        [
          "2|M|Virtual DOM, reconciliation, the diffing heuristics|Is the virtual DOM faster than direct DOM manipulation? Answer honestly.",
          "2|M|Keys in lists — why index-as-key is a real bug|Demonstrate a bug caused by index keys with a reorderable list of inputs.",
          "2|M|JSX — what it compiles to; fragments|",
          "2|M|Props, children, composition, render props|How do you avoid prop drilling without reaching for Redux?",
          "2|M|useState: batching, functional updates, state as a snapshot|Why does calling setCount(c+1) twice only increment once?",
          "2|M|Controlled vs uncontrolled components|",
          "2|M|Forms: validation, React Hook Form or Formik, error UX|",
          "2|M|Conditional rendering patterns and their pitfalls|Why does `count && <div/>` render a literal 0?",
          "2|M|Lifting state up|",
          "2|S|Synthetic events; event delegation in React|",
          "2|S|StrictMode double-invocation in development|Why does your effect run twice in dev, and what is it warning you about?",
        ],
      ],
      [
        "Hooks, in depth",
        [
          "2|M|The rules of hooks — and the reason behind them|Why can't hooks be called conditionally? What breaks?",
          "2|M|useEffect: dependency array, cleanup, run timing|",
          "2|M|useEffect pitfalls: infinite loops, stale closures, missing deps|Your effect reads stale state. Diagnose and fix it.",
          "2|M|Race conditions in data-fetching effects|Two fetches, the stale one resolves last. Fix it with a cleanup flag and with AbortController.",
          "2|M|You might not need an effect — derived state vs effects|When is deriving during render strictly better than syncing in an effect?",
          "2|M|useRef: DOM refs, mutable values, previous-value pattern|",
          "2|M|useMemo and useCallback — when they help and when they cost|Why does wrapping everything in useCallback make things slower?",
          "2|M|React.memo and referential equality|Show a case where React.memo does absolutely nothing.",
          "2|M|useReducer — when it beats useState|",
          "2|M|useContext — and why context re-renders everything below it|How do you stop a context update from re-rendering unrelated consumers?",
          "2|M|Custom hooks: useFetch, useDebounce, useLocalStorage, useOnClickOutside, usePrevious|Write three of these from memory.",
          "2|S|useLayoutEffect vs useEffect|When does the difference actually show up on screen?",
          "2|S|useId, useTransition, useDeferredValue|",
          "2|S|useImperativeHandle and forwardRef|",
          "2|E|useSyncExternalStore|How would you subscribe a component to an external store safely?",
          "2|S|Class lifecycle equivalents|componentDidMount, DidUpdate, WillUnmount, shouldComponentUpdate, getDerivedStateFromProps.",
        ],
      ],
      [
        "React internals and performance",
        [
          "2|M|Why did this component re-render? A systematic answer|Walk through every reason React re-renders a component.",
          "2|M|Finding wasted renders: Profiler, React DevTools, why-did-you-render|",
          "2|M|Code splitting: React.lazy, Suspense, route-based splitting|",
          "2|M|List virtualisation with react-window or virtuoso|At what list size does virtualisation start to matter?",
          "2|M|Error boundaries|Why don't error boundaries catch errors in event handlers or async code?",
          "2|S|Fiber architecture: render phase vs commit phase|",
          "2|S|Concurrent rendering and automatic batching in React 18|What changed about batching between React 17 and 18?",
          "2|S|Portals — modals, tooltips, and the z-index escape hatch|",
          "2|S|Suspense for data fetching|",
          "2|E|React Server Components vs Client Components|What can and cannot run in an RSC, and why?",
          "2|E|Reconciliation edge cases: same position different type, remounting|",
        ],
      ],
      [
        "State management",
        [
          "2|M|Server state vs client state vs UI state|The single most useful distinction in modern frontend. Explain it.",
          "2|M|Context + useReducer as a Redux alternative|Where does this pattern break down?",
          "2|M|Redux core: store, actions, reducers, immutability, middleware|",
          "2|M|Redux Toolkit: createSlice, createAsyncThunk, RTK Query|",
          "2|M|TanStack Query: caching, staleTime vs gcTime, invalidation, optimistic updates|What problem does React Query solve that Redux never did?",
          "2|M|When would you NOT use Redux?|",
          "2|S|Redux Thunk vs Saga|",
          "2|S|Zustand, Jotai, Recoil — and a defensible opinion|",
          "2|S|Optimistic updates and rollback|",
          "2|E|Normalising state shape; entity adapters|",
        ],
      ],
      [
        "Routing and frameworks",
        [
          "2|M|React Router: routes, nested routes, params, useNavigate, protected routes|",
          "2|M|CSR vs SSR vs SSG vs ISR|Given a marketing site, a dashboard and a blog — pick a rendering strategy for each and justify it.",
          "2|M|Next.js: app router vs pages router, server components, server actions|",
          "2|M|Hydration and hydration mismatch errors|What causes 'text content did not match' and how do you fix it?",
          "2|S|Next.js API routes, middleware, image optimisation|",
          "2|S|Data loading patterns: loaders, actions, streaming|",
          "2|E|Micro-frontends and Module Federation — the honest tradeoffs|",
        ],
      ],
      [
        "CSS and styling",
        [
          "2|M|Box model and box-sizing|",
          "2|M|Position: static, relative, absolute, fixed, sticky|Why did your sticky header stop sticking?",
          "2|M|Flexbox: every property, flex shorthand, common layouts|What does `flex: 1` expand to?",
          "2|M|CSS Grid: template areas, auto-fit vs auto-fill, minmax|Build a responsive card grid with no media queries.",
          "2|M|Specificity, cascade, inheritance, and !important|Calculate specificity for three competing selectors.",
          "2|M|Units: px, rem, em, %, vh, vw, ch, clamp|Why rem over px for typography?",
          "2|M|Media queries and mobile-first ordering|",
          "2|M|Centring a div — every method and when each applies|",
          "2|M|Stacking context and z-index bugs|Why doesn't z-index: 9999 work here?",
          "2|S|Pseudo-classes and pseudo-elements|",
          "2|S|Transitions, transforms, keyframes; what triggers reflow vs repaint vs composite|Which CSS properties are cheap to animate, and why?",
          "2|S|CSS custom properties and theming, including dark mode|",
          "2|S|Tailwind vs CSS Modules vs styled-components — tradeoffs|",
          "2|S|Responsive images: srcset, sizes, picture, aspect-ratio|",
          "2|E|Container queries, :has(), cascade layers, logical properties|",
        ],
      ],
      [
        "Browser and the web platform",
        [
          "2|M|What happens when you type a URL and press enter|The classic. Go from DNS all the way to first paint.",
          "2|M|Critical rendering path: DOM, CSSOM, render tree, layout, paint, composite|",
          "2|M|script defer vs async vs neither|",
          "2|M|Reflow vs repaint; layout thrashing|Spot the thrash in a loop that reads offsetHeight and writes styles.",
          "2|M|Cookies vs localStorage vs sessionStorage vs IndexedDB|Compare on size, expiry, sync/async and whether they hit the server.",
          "2|M|Cookie attributes: HttpOnly, Secure, SameSite, domain, path|Where do you store a JWT, and defend the choice.",
          "2|M|CORS: preflight, the Allow headers, credentials|A request works in Postman but fails in the browser. Explain, then fix it properly.",
          "2|M|HTTP caching: Cache-Control, ETag, Last-Modified, max-age, no-cache vs no-store|",
          "2|M|Core Web Vitals: LCP, INP, CLS, TTFB, FCP|Name a concrete fix for each one.",
          "2|M|Debugging with DevTools: network, performance, memory, coverage|",
          "2|S|Fetch API, headers, FormData, streaming, file uploads|",
          "2|S|Web Workers — moving CPU work off the main thread|",
          "2|S|Service workers, PWA, offline caching strategies|",
          "2|S|WebSockets vs SSE vs long polling|Which would you pick for a live dashboard, and for a chat app?",
          "2|S|Bundle analysis and performance budgets|",
          "2|E|Intersection, Resize and Mutation Observers|",
          "2|E|Web Vitals measurement in production, RUM vs lab data|",
        ],
      ],
      [
        "Accessibility, SEO and frontend security",
        [
          "2|M|Semantic HTML and why div soup fails|",
          "2|M|Keyboard navigation, focus management, focus trapping in modals|",
          "2|M|ARIA roles, labels, live regions — and the first rule of ARIA|",
          "2|M|Colour contrast, alt text, form labelling|",
          "2|M|XSS: stored, reflected, DOM-based|How does React protect you, and where does it stop? dangerouslySetInnerHTML.",
          "2|M|CSRF — what it is and how SameSite plus tokens stop it|",
          "2|S|Content Security Policy|",
          "2|S|Clickjacking and X-Frame-Options|",
          "2|S|SEO: meta tags, Open Graph, sitemaps, robots.txt, structured data|",
          "2|S|Screen reader testing basics|",
          "2|E|Internationalisation: locale formatting, RTL, pluralisation|",
        ],
      ],
    ],
  },
  {
    number: "03",
    id: "node",
    name: "Node.js & Express",
    blurb:
      "Your strongest existing ground — which means the bar is higher. Expect questions about the event loop under load, streams, graceful shutdown and everything you have quietly let a framework handle for you.",
    groups: [
      [
        "Node fundamentals",
        [
          "3|M|What Node actually is: V8 plus libuv|Is Node single-threaded? Answer precisely — it is a trick question.",
          "3|M|The Node event loop phases|timers, pending callbacks, poll, check, close. Where does I/O actually resume?",
          "3|M|process.nextTick vs setImmediate vs Promise microtasks|Predict the output order of all three.",
          "3|M|Blocking the event loop|A JSON.parse of a 50MB payload stalls every request. Explain why and fix it.",
          "3|M|worker_threads vs child_process vs cluster|Which do you reach for to hash passwords for 10k users, and why?",
          "3|M|Streams: readable, writable, duplex, transform; piping|Copy a 5GB file without exhausting memory.",
          "3|M|Backpressure — what it is and what ignoring it does|",
          "3|M|Buffers and binary data|",
          "3|M|EventEmitter — and implement your own|",
          "3|M|Error handling: operational vs programmer errors, uncaughtException, unhandledRejection|Should you keep the process alive after an uncaught exception? Justify it.",
          "3|M|Graceful shutdown on SIGTERM with in-flight requests|Write the shutdown handler.",
          "3|S|fs sync vs async vs promises; reading large files|",
          "3|S|CommonJS module resolution, the require cache, circular requires|",
          "3|S|process: argv, env, exit codes, signals|",
          "3|S|util.promisify, path, os, crypto|",
          "3|S|Memory limits, --max-old-space-size, heap snapshots|",
          "3|S|Profiling with --inspect, clinic.js, flame graphs|How do you find which endpoint is burning CPU in production?",
          "3|E|Native addons and N-API|",
          "3|E|Node internals: libuv thread pool sizing (UV_THREADPOOL_SIZE)|",
        ],
      ],
      [
        "Express and API design",
        [
          "3|M|The request lifecycle; how middleware chaining works|Implement a mini Express with app.use and next().",
          "3|M|Middleware types and ordering|Why does your auth middleware not run for this route?",
          "3|M|next() vs next(err); the async error trap|Why does a rejected promise in an async handler hang the request in Express 4?",
          "3|M|Routing, route params, query strings, Router modules|",
          "3|M|HTTP status codes that carry meaning|200 vs 201 vs 204, 400 vs 401 vs 403 vs 404 vs 409 vs 422 vs 429.",
          "3|M|REST principles, resource naming, idempotency|Which HTTP methods are idempotent? Why does it matter for retries?",
          "3|M|Validation at the boundary with Zod or Joi|",
          "3|M|Centralised error handling and custom error classes|Design the error response shape for a public API.",
          "3|M|Pagination: offset vs cursor/keyset|Why does OFFSET 100000 get slow, and what replaces it?",
          "3|M|Filtering, sorting, field selection|",
          "3|M|API versioning strategies|",
          "3|M|Rate limiting in Express, and doing it correctly behind a load balancer|",
          "3|M|Structured logging with pino or winston; correlation IDs|How do you trace one user request across three services?",
          "3|M|Health checks: liveness vs readiness|",
          "3|M|Caching layer: cache-aside with Redis, TTLs, invalidation|",
          "3|M|Background jobs with BullMQ: retries, backoff, dead-letter, idempotency|Your email job ran twice. How do you make it safe?",
          "3|S|File uploads: multer, streaming to S3, presigned URLs|Why is a presigned URL better than proxying the upload through your server?",
          "3|S|Compression, helmet, CORS configuration|",
          "3|S|Request timeouts and circuit breakers|",
          "3|S|Webhooks: signature verification, replay protection, retries|",
          "3|S|OpenAPI/Swagger documentation|",
          "3|S|Clustering vs container replicas; PM2|",
          "3|S|Long-running requests, SSE and WebSockets in Express|",
          "3|E|GraphQL: schema, resolvers, N+1 and DataLoader|When is GraphQL the wrong choice?",
          "3|E|tRPC and end-to-end type safety|",
          "3|E|NestJS: modules, providers, dependency injection, decorators|Increasingly asked at product companies.",
          "3|E|Fastify vs Express — why teams migrate|",
        ],
      ],
      [
        "Authentication, authorisation and security",
        [
          "3|M|Authentication vs authorisation|",
          "3|M|Sessions plus cookies vs JWT|Give a scenario where sessions beat JWT, and one where the reverse is true.",
          "3|M|JWT anatomy: header, payload, signature; HS256 vs RS256|Can you decode a JWT without the secret? What does that imply about payload contents?",
          "3|M|Access tokens, refresh tokens, rotation, revocation|How do you log a user out of a stateless JWT system?",
          "3|M|Where to store tokens: httpOnly cookie vs localStorage|Argue both sides, then pick one.",
          "3|M|Password hashing: bcrypt or argon2, salting, work factor|Why is SHA-256 the wrong tool for passwords?",
          "3|M|RBAC vs ABAC; permission middleware design|",
          "3|M|SQL injection and NoSQL injection|Show a vulnerable query and its parameterised fix.",
          "3|M|OWASP Top 10 — name them and explain each|",
          "3|M|IDOR — the most common real-world API bug|Your endpoint is /orders/:id. What is missing?",
          "3|M|Secrets management; never committing keys; env var hygiene|",
          "3|S|OAuth 2.0 authorisation code flow with PKCE; OpenID Connect|Walk through Google sign-in end to end.",
          "3|S|HTTPS and the TLS handshake; certificates and the CA chain|",
          "3|S|SSRF, mass assignment, prototype pollution|",
          "3|S|Multi-tenancy and data isolation|",
          "3|S|Audit logging and PII handling|",
          "3|E|mTLS, service-to-service auth, short-lived credentials|",
          "3|E|Encryption at rest vs in transit; key rotation|",
        ],
      ],
    ],
  },
  {
    number: "04",
    id: "db",
    name: "Databases: Postgres, MongoDB, Redis",
    blurb:
      "The track that most often decides a backend offer. Writing queries is table stakes — they will ask you to read a query plan, pick an index, choose an isolation level and defend a schema.",
    groups: [
      [
        "SQL and PostgreSQL fundamentals",
        [
          "4|M|Relational model; primary, foreign, composite, surrogate vs natural keys|",
          "4|M|Postgres data types: text vs varchar, numeric vs float, timestamptz vs timestamp, uuid, jsonb, arrays, enums|Why timestamptz over timestamp, always?",
          "4|M|Constraints: NOT NULL, UNIQUE, CHECK, FK with ON DELETE CASCADE or SET NULL|",
          "4|M|SELECT: WHERE, ORDER BY, LIMIT, OFFSET, DISTINCT|",
          "4|M|Joins: INNER, LEFT, RIGHT, FULL, CROSS, SELF|Draw each one. How many rows does a LEFT JOIN return?",
          "4|M|Aggregations: COUNT, SUM, AVG, MIN, MAX, GROUP BY, HAVING|What is the difference between WHERE and HAVING?",
          "4|M|NULL semantics and three-valued logic|Why does `WHERE col != 'x'` skip NULL rows? COALESCE and NULLIF.",
          "4|M|Subqueries, correlated subqueries; EXISTS vs IN vs JOIN|Which performs best on a large table, and why?",
          "4|M|CTEs with WITH; recursive CTEs|Query an org chart or a category tree recursively.",
          "4|M|Window functions: ROW_NUMBER, RANK, DENSE_RANK, LAG, LEAD, SUM OVER, PARTITION BY|Extremely commonly asked. Know the RANK vs DENSE_RANK vs ROW_NUMBER difference cold.",
          "4|M|UNION vs UNION ALL; INTERSECT; EXCEPT|",
          "4|M|Upsert with ON CONFLICT; RETURNING|",
          "4|M|CASE expressions and conditional aggregation|Pivot rows into columns without a pivot function.",
          "4|S|Views and materialised views|When is a materialised view the right answer?",
          "4|S|Generated columns, identity columns, sequences|",
        ],
      ],
      [
        "Indexing, plans and query performance",
        [
          "4|M|How a B-tree index works|Why does an index make writes slower?",
          "4|M|Index types: B-tree, hash, GIN, GiST, BRIN|Which index type for a jsonb containment query? For full-text?",
          "4|M|Composite indexes and column order|Does an index on (a,b) help a query filtering only on b?",
          "4|M|Covering indexes, partial indexes, unique indexes|",
          "4|M|When an index is NOT used|Functions on indexed columns, leading wildcards, low selectivity, type mismatches.",
          "4|M|EXPLAIN ANALYZE — reading a query plan|Seq scan vs index scan vs bitmap heap scan; nested loop vs hash join vs merge join.",
          "4|M|The N+1 query problem|Show it in an ORM and fix it three ways.",
          "4|M|Query optimisation checklist|SELECT *, OR vs UNION, keyset pagination, avoiding sorts, index-only scans.",
          "4|S|Table statistics, ANALYZE, and why the planner picks badly|",
          "4|S|Slow query logging and pg_stat_statements|How do you find your worst query in production?",
        ],
      ],
      [
        "Transactions and concurrency",
        [
          "4|M|ACID — explain each letter with a real example|",
          "4|M|Isolation levels: read committed, repeatable read, serializable|",
          "4|M|Read phenomena: dirty read, non-repeatable read, phantom read|Map each phenomenon to the isolation level that prevents it.",
          "4|M|SELECT FOR UPDATE and row-level locking|Two users book the last seat simultaneously. Prevent the double booking.",
          "4|M|Deadlocks: how they happen, how to avoid them|",
          "4|M|Optimistic vs pessimistic concurrency; version columns|",
          "4|S|MVCC in Postgres; VACUUM, table bloat, autovacuum|",
          "4|S|Savepoints and nested transactions|",
          "4|S|Transactions across HTTP requests — and why you should not|",
          "4|E|Transaction ID wraparound|",
          "4|E|Advisory locks|",
        ],
      ],
      [
        "Schema design and operations",
        [
          "4|M|Normalisation: 1NF, 2NF, 3NF, BCNF; update/insert/delete anomalies|",
          "4|M|Denormalisation — when it is the right call|",
          "4|M|Modelling relationships: one-to-many, many-to-many, join tables, polymorphic associations|",
          "4|M|Soft deletes, audit columns, created_at/updated_at|",
          "4|M|Connection pooling: pg Pool, PgBouncer, pool sizing|Why does raising the pool size sometimes make things slower?",
          "4|M|Migrations: Prisma Migrate, Knex, TypeORM|",
          "4|M|Zero-downtime migrations — the expand and contract pattern|How do you rename a column with no downtime?",
          "4|S|Replication: streaming, read replicas, replication lag|A user writes then immediately reads and sees stale data. Explain and fix.",
          "4|S|Partitioning and sharding in Postgres|",
          "4|S|ORMs: Prisma vs TypeORM vs Sequelize vs Knex; when to drop to raw SQL|",
          "4|S|jsonb: querying, operators, indexing|",
          "4|S|Full-text search with tsvector vs reaching for Elasticsearch|",
          "4|S|Backups, PITR, restore drills|",
          "4|E|Triggers and stored procedures — and why many teams avoid them|",
          "4|E|Row-level security|",
          "4|E|Extensions: PostGIS, pg_trgm, pgcrypto, TimescaleDB|",
        ],
      ],
      [
        "SQL problems to solve by hand",
        [
          "4|M|Second and Nth highest salary|Three ways: subquery, DENSE_RANK, LIMIT/OFFSET.",
          "4|M|Top N per group|Highest-paid employee per department.",
          "4|M|Find and delete duplicate rows|",
          "4|M|Running totals and cumulative sums|",
          "4|M|Month-over-month and year-over-year growth|",
          "4|M|Consecutive days or streaks|Users who logged in three days in a row.",
          "4|M|Employees earning more than their manager (self-join)|",
          "4|M|Rows in table A with no match in table B|Three ways: LEFT JOIN IS NULL, NOT EXISTS, EXCEPT.",
          "4|S|Gaps and islands|",
          "4|S|Median and percentiles|",
          "4|S|Pivoting rows to columns|",
          "4|S|Cohort retention query|",
        ],
      ],
      [
        "MongoDB",
        [
          "4|M|Document model, BSON, collections|",
          "4|M|When NoSQL beats SQL — and the honest counterargument|You have this app. Postgres or Mongo? Defend the choice.",
          "4|M|CRUD and query operators|$gt, $in, $nin, $regex, $exists, $elemMatch, $all.",
          "4|M|Update operators|$set, $unset, $inc, $push, $pull, $addToSet, $pop, upsert.",
          "4|M|The aggregation pipeline|$match, $group, $project, $sort, $limit, $unwind, $lookup, $facet, $addFields.",
          "4|M|Why $match must come first|Explain the performance implication of pipeline stage order.",
          "4|M|$lookup — the joins Mongo said it did not need|What are its limits versus a SQL join?",
          "4|M|Indexes: single, compound, multikey, text, TTL, partial, unique|",
          "4|M|The ESR rule for compound index order|Equality, Sort, Range. Explain why.",
          "4|M|explain() and reading a Mongo plan|COLLSCAN vs IXSCAN.",
          "4|M|Schema design: embed vs reference|One-to-few, one-to-many, one-to-squillions. Give the rule of thumb.",
          "4|M|The 16MB document limit and unbounded array growth|",
          "4|M|Mongoose: schemas, validation, middleware hooks, populate, lean, virtuals|Why is populate secretly an N+1?",
          "4|S|Transactions in MongoDB and the replica set requirement|",
          "4|S|Replica sets, elections, write concern, read preference, read concern|What does `w: majority` guarantee?",
          "4|S|Sharding: shard key selection, chunks, hot-spotting|Why is a monotonically increasing shard key a bad idea?",
          "4|S|Design patterns: extended reference, bucket, computed, subset, outlier|",
          "4|E|Change streams|",
          "4|E|Capped collections and GridFS|",
          "4|E|Atlas Search and vector search|",
        ],
      ],
      [
        "Redis and caching",
        [
          "4|M|Redis data types and a use case for each|string, hash, list, set, sorted set, bitmap, stream.",
          "4|M|Cache-aside, read-through, write-through, write-behind|Which do you use, and what is the failure mode of each?",
          "4|M|TTL, expiry, and eviction policies (LRU, LFU, volatile-*)|What happens when Redis fills up?",
          "4|M|Cache invalidation strategies|The hardest problem in computer science. What are your options?",
          "4|M|Cache stampede and the thundering herd|A hot key expires and 5000 requests hit the DB at once. Prevent it.",
          "4|M|Redis as a rate limiter|Implement a sliding-window counter with INCR and EXPIRE.",
          "4|M|Redis as a session store|",
          "4|S|Distributed locks and the Redlock debate|",
          "4|S|Persistence: RDB vs AOF|",
          "4|S|Pub/Sub vs Streams|",
          "4|S|Sorted sets for leaderboards and delayed queues|",
          "4|E|Redis Cluster, Sentinel, hash slots|",
          "4|E|Pipelining and Lua scripts for atomicity|",
        ],
      ],
    ],
  },
  {
    number: "05",
    id: "sd",
    name: "System Design (HLD)",
    blurb:
      "The round that most often separates a 12 LPA offer from a 30 LPA one. You are not expected to know the right answer — you are expected to ask clarifying questions, estimate, propose, and name your own tradeoffs before the interviewer does.",
    groups: [
      [
        "Building blocks",
        [
          "5|M|The interview framework: requirements, estimates, API, data model, high level, deep dive, bottlenecks|Rehearse this structure until it is automatic. Never start by drawing boxes.",
          "5|M|Functional vs non-functional requirements|Which three questions do you always ask in the first five minutes?",
          "5|M|Back-of-envelope estimation: QPS, storage, bandwidth, memory|100M users, 10 posts a day. Size the system.",
          "5|M|Latency numbers every engineer should know|Memory vs SSD vs network vs cross-region round trip.",
          "5|M|Vertical vs horizontal scaling|",
          "5|M|Load balancers: L4 vs L7, round robin, least connections, health checks, sticky sessions|",
          "5|M|Stateless services and why state is the enemy of scaling|",
          "5|M|Caching at every layer: browser, CDN, reverse proxy, application, database|",
          "5|M|CDNs — how they work, cache invalidation, edge compute|",
          "5|M|Database scaling: read replicas, sharding, federation, denormalisation|",
          "5|M|Sharding strategies: range, hash, directory; resharding pain|",
          "5|M|Consistent hashing|Draw the ring. Why does it beat modulo hashing when a node dies?",
          "5|M|CAP theorem — and why it is more subtle than pick two|",
          "5|M|Consistency models: strong, eventual, read-your-writes, monotonic, causal|",
          "5|M|Message queues: Kafka vs RabbitMQ vs SQS|When Kafka, when RabbitMQ? Name the deciding factor.",
          "5|M|Delivery semantics: at-most-once, at-least-once, exactly-once|Why is exactly-once mostly a lie, and what do you do instead?",
          "5|M|Idempotency keys and idempotent consumers|",
          "5|M|Dead letter queues, retries with jitter, poison messages|",
          "5|M|Synchronous vs asynchronous communication|Which parts of a checkout flow must be sync, and which must not?",
          "5|M|Rate limiting algorithms|Fixed window, sliding log, sliding counter, token bucket, leaky bucket. Implement one.",
          "5|M|Unique ID generation at scale|UUID v4 vs v7 vs ULID vs Snowflake. Why is a UUID v4 primary key bad for a B-tree?",
          "5|M|Monolith vs microservices vs modular monolith|You have a 6-person team. Which, and why?",
          "5|M|API gateway, BFF pattern, service discovery|",
          "5|M|Circuit breaker, bulkhead, timeouts, graceful degradation|",
          "5|M|Observability: metrics, logs, traces; SLI, SLO, SLA, error budgets|",
          "5|S|Saga pattern, two-phase commit, the transactional outbox|How do you keep a DB write and a Kafka publish consistent?",
          "5|S|Event sourcing and CQRS|",
          "5|S|Search: inverted index, Elasticsearch basics, relevance|",
          "5|S|Blob storage, S3, presigned URLs, multipart upload|",
          "5|S|WebSockets at scale: connection state, sticky routing, pub/sub fanout|",
          "5|S|Availability maths, redundancy, failover, RPO and RTO|",
          "5|S|Load testing with k6 or Artillery|",
          "5|E|Bloom filters and count-min sketch|",
          "5|E|Leader election, Raft, ZooKeeper/etcd|",
          "5|E|Geo-distribution, multi-region active-active, data residency|",
          "5|E|Vector clocks and conflict resolution (CRDTs)|",
        ],
      ],
      [
        "Design questions to actually practise out loud",
        [
          "5|M|Design a URL shortener|The warm-up. Key generation, collisions, redirects, analytics, cache.",
          "5|M|Design a rate limiter as a service|",
          "5|M|Design a news feed (Twitter/Instagram)|Fanout on write vs fanout on read. Handle the celebrity problem.",
          "5|M|Design a chat application (WhatsApp)|WebSockets, presence, delivery receipts, ordering, offline messages.",
          "5|M|Design a notification system|Push, email, SMS; fanout, deduplication, user preferences, retries.",
          "5|M|Design an e-commerce checkout with inventory|Prevent overselling. Reservations, timeouts, idempotent payment.",
          "5|M|Design a ticket-booking system (BookMyShow)|Seat locking under concurrency is the whole question.",
          "5|M|Design a food delivery or ride-hailing system|Geospatial indexing, matching, order state machine, live tracking.",
          "5|M|Design a file storage and sync service (Dropbox)|Chunking, deduplication, conflict resolution, sync protocol.",
          "5|S|Design a video platform (YouTube/Netflix)|Upload, transcoding pipeline, adaptive bitrate, CDN.",
          "5|S|Design typeahead/autocomplete|Trie, ranking, caching, debounce on the client.",
          "5|S|Design a payment system|Idempotency, ledger, double-entry bookkeeping, reconciliation, webhooks.",
          "5|S|Design a web crawler|",
          "5|S|Design a distributed job scheduler or cron service|",
          "5|S|Design a logging and monitoring pipeline|",
          "5|S|Design a multi-tenant SaaS application|Data isolation strategies and their tradeoffs.",
          "5|S|Design a feature-flag service|",
          "5|E|Design Google Docs (collaborative editing)|OT vs CRDT — awareness is enough.",
          "5|E|Design an analytics/event ingestion pipeline|",
          "5|E|Design a distributed cache|",
        ],
      ],
      [
        "Frontend system design",
        [
          "5|M|Component architecture and a design system|How do you structure a large React codebase so it stays navigable?",
          "5|M|Client-side data layer: caching, invalidation, optimistic updates|",
          "5|M|Design an autocomplete component|Debounce, cancellation, caching, keyboard nav, accessibility, race conditions.",
          "5|M|Design an infinite-scrolling virtualised feed|",
          "5|M|Frontend performance strategy|Bundle budget, code splitting plan, image strategy, font loading, prefetching.",
          "5|S|Design an image gallery with lazy loading|",
          "5|S|Design an offline-first app with background sync|",
          "5|S|Design a real-time dashboard|Polling vs SSE vs WebSocket, and how you decide.",
          "5|S|Error handling, retry and loading-state architecture|",
          "5|S|Analytics and event tracking architecture|",
          "5|E|Micro-frontends: when the org problem justifies the technical cost|",
          "5|E|Design a rich text editor|",
        ],
      ],
    ],
  },
  {
    number: "06",
    id: "lld",
    name: "Low-Level Design & Machine Coding",
    blurb:
      "Product companies increasingly run a 90-minute round where you build something small but real. They are grading structure, naming, extensibility and tests — not cleverness.",
    groups: [
      [
        "Principles and patterns",
        [
          "3|M|SOLID — all five, each with a real example from your own code|Give a concrete violation you have personally fixed.",
          "3|M|DRY, KISS, YAGNI, composition over inheritance, law of Demeter|",
          "3|M|Layering: controller, service, repository|Why should a controller never touch the database?",
          "3|M|Dependency injection and inversion of control|",
          "3|M|Creational patterns: Singleton, Factory, Abstract Factory, Builder|",
          "3|M|Structural patterns: Adapter, Decorator, Facade, Proxy|",
          "3|M|Behavioural patterns: Observer, Strategy, Command, State, Chain of Responsibility, Template Method|Which pattern replaces a growing if/else chain?",
          "3|M|Repository pattern and why it makes testing possible|",
          "3|S|Clean and hexagonal architecture; ports and adapters|",
          "3|S|Domain modelling: entities, value objects, aggregates|",
          "3|S|Code smells and refactoring moves|",
          "3|E|Anti-patterns: God object, anaemic domain model, service locator|",
        ],
      ],
      [
        "Machine coding problems",
        [
          "3|M|In-memory key-value store with TTL|",
          "3|M|LRU cache from scratch (map plus doubly linked list)|",
          "3|M|Rate limiter (token bucket) as a reusable class|",
          "3|M|Parking lot system|",
          "3|M|Splitwise / expense sharing|",
          "3|M|Design a URL shortener as working code, not a diagram|",
          "3|M|Task or job scheduler with retries|",
          "3|S|Elevator system|",
          "3|S|Vending machine or ATM (state pattern)|",
          "3|S|BookMyShow seat booking|",
          "3|S|Tic-tac-toe, snake and ladder, or chess|",
          "3|S|Logging framework with pluggable appenders|",
          "3|S|Notification service with multiple channels|",
          "3|S|Library management system|",
          "3|M|Practise the format itself|90 minutes, working code, clean folder structure, a few tests, a README explaining tradeoffs. Do three timed runs.",
        ],
      ],
    ],
  },
  {
    number: "07",
    id: "dsa",
    name: "DSA & Problem Solving",
    blurb:
      "Do this every single day from day one — it decays faster than anything else here. Target 150 to 200 problems, spoken aloud, timed, in a plain editor with no autocomplete.",
    groups: [
      [
        "Foundations",
        [
          "1|M|Big-O, big-Theta, big-Omega; time and space complexity|Analyse a nested loop, a recursive call, and a function with a hash map.",
          "1|M|Amortised analysis|Why is push to a dynamic array O(1) amortised?",
          "1|M|Recursion: base cases, call stack, recursion trees|",
          "1|M|Complexity of JavaScript operations|shift, unshift, splice, spread, object key lookup, Map vs object.",
          "1|S|Space complexity of recursion vs iteration|",
        ],
      ],
      [
        "Arrays, strings and hashing",
        [
          "1|M|Two pointers|Two sum sorted, three sum, container with most water, remove duplicates, sort colours.",
          "1|M|Sliding window, fixed and variable size|Longest substring without repeating characters, minimum window substring, max sum subarray of size k.",
          "1|M|Prefix sums and difference arrays|Subarray sum equals k, range sum queries.",
          "1|M|Hash maps and sets|Two sum, group anagrams, longest consecutive sequence, frequency counting.",
          "1|M|Kadane's algorithm|Maximum subarray, maximum product subarray.",
          "1|M|String manipulation|Palindromes, anagrams, string compression, reverse words, roman numerals.",
          "1|M|Matrix problems|Spiral traversal, rotate image, set matrix zeroes, search a 2D matrix.",
          "1|S|Cyclic sort and finding missing/duplicate numbers|",
          "1|S|Dutch national flag partitioning|",
        ],
      ],
      [
        "Linked lists, stacks and queues",
        [
          "2|M|Linked list basics: traverse, insert, delete, reverse (iterative and recursive)|",
          "2|M|Fast and slow pointers|Cycle detection (Floyd), find the middle, find cycle start.",
          "2|M|Merge two sorted lists; merge k sorted lists|",
          "2|M|Reverse in groups of k; palindrome linked list; reorder list|",
          "2|M|Stacks: valid parentheses, min stack, evaluate RPN|",
          "2|M|Monotonic stack|Next greater element, daily temperatures, largest rectangle in histogram, trapping rain water.",
          "2|M|Queues and deques|Sliding window maximum, implement a queue using stacks.",
          "2|M|LRU cache — the single most-asked design-flavoured problem|",
          "2|S|LFU cache|",
          "2|S|Doubly linked lists and their use in caches|",
        ],
      ],
      [
        "Trees and tries",
        [
          "3|M|Traversals: preorder, inorder, postorder (recursive and iterative), level order|",
          "3|M|DFS vs BFS on trees — and when each is right|",
          "3|M|Height, diameter, balanced check, same tree, symmetric tree, invert tree|",
          "3|M|BST: search, insert, delete, validate, kth smallest, inorder successor|Why does an inorder traversal of a BST give sorted output?",
          "3|M|Lowest common ancestor, in a BST and in a general binary tree|",
          "3|M|Path problems: root-to-leaf sum, max path sum, all paths|",
          "3|M|Serialise and deserialise a binary tree|",
          "3|M|Tree views: left, right, top, bottom; vertical order traversal|",
          "3|M|Tries: implement insert, search, startsWith|Word search II, autocomplete, longest common prefix.",
          "3|S|Construct a tree from preorder and inorder traversals|",
          "3|S|Binary tree to doubly linked list; flatten to linked list|",
          "3|E|Segment trees and Fenwick trees|",
        ],
      ],
      [
        "Heaps, greedy and intervals",
        [
          "4|M|Heaps and priority queues — implement a min heap|",
          "4|M|Top K problems|K largest elements, top K frequent, K closest points.",
          "4|M|K-way merge; median from a data stream (two heaps)|",
          "4|M|Task scheduler; reorganise string|",
          "4|M|Interval problems|Merge intervals, insert interval, non-overlapping intervals, meeting rooms I and II.",
          "4|M|Greedy: jump game, gas station, activity selection, partition labels|When is greedy provably correct?",
          "4|S|Sweep line technique|",
        ],
      ],
      [
        "Graphs",
        [
          "4|M|Representations: adjacency list vs matrix; building a graph from edges|",
          "4|M|BFS and DFS on graphs; connected components|",
          "4|M|Grid as a graph|Number of islands, rotting oranges, flood fill, shortest path in a binary maze, word ladder.",
          "4|M|Cycle detection, directed and undirected|",
          "4|M|Topological sort (Kahn's and DFS)|Course schedule I and II, alien dictionary.",
          "4|M|Dijkstra's shortest path|Network delay time, cheapest flights within k stops.",
          "4|M|Union-Find with path compression and union by rank|Number of provinces, redundant connection, accounts merge.",
          "4|S|Bellman-Ford and Floyd-Warshall|",
          "4|S|Minimum spanning tree: Kruskal and Prim|",
          "4|S|Bipartite check and graph colouring|",
          "4|E|Tarjan's algorithm, bridges and articulation points|",
        ],
      ],
      [
        "Binary search, sorting and bit manipulation",
        [
          "5|M|Binary search on a sorted array; first and last occurrence|Get the boundary conditions right without guessing.",
          "5|M|Binary search on the answer|Koko eating bananas, split array largest sum, capacity to ship packages, minimum in rotated array.",
          "5|M|Search in a rotated sorted array; find peak element|",
          "5|M|Median of two sorted arrays|",
          "5|M|Sorting algorithms: bubble, selection, insertion, merge, quick, heap, counting, radix|Complexity, stability, and when each is actually used.",
          "5|M|Quickselect for the kth largest|",
          "5|M|Bit manipulation basics|XOR tricks, single number, count set bits, power of two, swap without temp.",
          "5|S|Subsets via bitmask|",
          "5|S|What algorithm does JavaScript's Array.sort use?|",
        ],
      ],
      [
        "Backtracking and dynamic programming",
        [
          "5|M|Backtracking template|Subsets, permutations, combinations, combination sum.",
          "5|M|N-Queens, sudoku solver, word search, palindrome partitioning, rat in a maze|",
          "5|M|Memoisation vs tabulation; how to spot a DP problem|What are the two signals that a problem is DP?",
          "5|M|1D DP|Climbing stairs, house robber I and II, decode ways, jump game.",
          "5|M|Knapsack family|0/1 knapsack, unbounded knapsack, subset sum, equal partition, target sum, coin change.",
          "5|M|String DP|Longest common subsequence, edit distance, longest palindromic substring, distinct subsequences.",
          "5|M|Longest increasing subsequence (n^2 and n log n)|",
          "5|M|Grid DP|Unique paths, minimum path sum, with obstacles.",
          "5|M|Stock buy and sell — the whole series|One transaction, unlimited, with cooldown, with fee, at most k.",
          "5|S|Matrix chain multiplication and partition DP|",
          "5|E|DP with bitmask; digit DP|",
        ],
      ],
      [
        "Practice discipline",
        [
          "1|M|Work Blind 75 first, then NeetCode 150|",
          "1|M|Timebox to 25 minutes, then read the solution and re-solve from scratch two days later|",
          "1|M|Say the approach and complexity out loud before writing a line of code|This is what the interviewer is actually grading.",
          "1|M|Always state edge cases: empty input, single element, duplicates, negatives, overflow|",
          "1|M|Dry run your code on an example before saying you are done|",
          "2|M|Keep a mistakes log and revisit it weekly|",
          "5|S|Do company-tagged problem sets once you have real interviews scheduled|",
        ],
      ],
    ],
  },
  {
    number: "08",
    id: "cs",
    name: "CS Fundamentals & Git",
    blurb:
      "Service-based and MNC loops lean on these hard, and product companies use them as a sanity check. Cheap to learn, embarrassing to miss.",
    groups: [
      [
        "Operating systems",
        [
          "6|M|Process vs thread; context switching|",
          "6|M|Concurrency vs parallelism|Explain the difference using Node as the example.",
          "6|M|Deadlock: the four necessary conditions, prevention, avoidance, detection|",
          "6|M|Race conditions, mutex vs semaphore, critical sections|",
          "6|M|Virtual memory, paging, page faults, thrashing|",
          "6|S|CPU scheduling algorithms: FCFS, SJF, round robin, priority|",
          "6|S|Producer-consumer and reader-writer problems|",
          "6|S|IPC mechanisms: pipes, shared memory, message queues, sockets|",
          "6|S|How Node's single-threaded model maps onto all of this|",
          "6|E|File systems, inodes, journaling|",
        ],
      ],
      [
        "Computer networks",
        [
          "6|M|What happens when you type a URL and press enter|Rehearse a 3-minute version and a 30-second version.",
          "6|M|OSI model vs TCP/IP model|",
          "6|M|TCP vs UDP; the three-way handshake and four-way teardown|Why does a video call use UDP and a file download use TCP?",
          "6|M|DNS resolution end to end; A, AAAA, CNAME, MX, TXT records; TTL and caching|",
          "6|M|HTTP methods, idempotency, safety, status codes|",
          "6|M|HTTP/1.1 vs HTTP/2 vs HTTP/3|Head-of-line blocking, multiplexing, header compression, QUIC.",
          "6|M|HTTPS and the TLS handshake; symmetric vs asymmetric encryption; certificates|",
          "6|M|REST vs GraphQL vs gRPC vs WebSocket|",
          "6|S|Flow control vs congestion control|",
          "6|S|Proxies, reverse proxies, NAT, firewalls|",
          "6|S|Ports, sockets, keep-alive, connection reuse|",
          "6|S|Where latency actually comes from|DNS, TCP, TLS, TTFB; bandwidth vs latency.",
          "6|E|Subnetting and CIDR basics|",
        ],
      ],
      [
        "DBMS theory",
        [
          "6|M|ER modelling, cardinality, relationship types|",
          "6|M|Functional dependencies and normalisation, with anomalies|",
          "6|M|B-tree vs B+ tree and why databases use B+ trees|",
          "6|M|ACID vs BASE|",
          "6|S|Concurrency control protocols: 2PL, timestamp ordering|",
          "6|S|Clustered vs non-clustered indexes|",
          "6|E|Write-ahead logging and recovery|",
        ],
      ],
      [
        "Git and collaboration",
        [
          "6|M|The three areas: working directory, staging, repository|",
          "6|M|Merge vs rebase|When would you rebase, and when is it dangerous?",
          "6|M|Resolving conflicts confidently|",
          "6|M|reset soft vs mixed vs hard; revert vs reset|You pushed a bad commit to main. What now?",
          "6|M|cherry-pick, stash, reflog|How do you recover a commit you thought you destroyed?",
          "6|M|Branching strategies: Git Flow, GitHub Flow, trunk-based|",
          "6|S|git bisect to find the commit that broke it|",
          "6|S|Interactive rebase, squashing, fixup commits|",
          "6|S|Tags, semantic versioning, release process|",
          "6|S|Code review etiquette and conventional commits|",
          "6|E|Submodules, sparse checkout, monorepo vs polyrepo|",
        ],
      ],
    ],
  },
  {
    number: "09",
    id: "ops",
    name: "DevOps, Cloud & Delivery",
    blurb:
      "You do not need to be an SRE. You do need to describe how your code reaches production without hand-waving — that single answer separates people who have shipped from people who have only committed.",
    groups: [
      [
        "Linux and the shell",
        [
          "5|M|File permissions, ownership, chmod and chown|",
          "5|M|Processes: ps, top, htop, kill, signals, nohup|",
          "5|M|Text processing: grep, awk, sed, cut, sort, uniq, wc|Find the top 10 IPs in an access log with one pipeline.",
          "5|M|Networking tools: curl, netstat, lsof, dig, telnet|A port is in use. Find what is holding it.",
          "5|S|ssh, scp, key-based auth|",
          "5|S|systemd services, journalctl, cron|",
          "5|S|Disk and memory: df, du, free|",
          "5|S|Basic shell scripting: variables, conditionals, loops, exit codes|",
        ],
      ],
      [
        "Containers and orchestration",
        [
          "5|M|Images vs containers; how layers and caching work|Why does reordering your Dockerfile speed up builds?",
          "5|M|Writing a good Dockerfile for a Node app|Multi-stage build, non-root user, .dockerignore, small base image.",
          "5|M|Volumes, networks, port mapping, environment variables|",
          "5|M|docker-compose for local development|",
          "5|M|Container vs virtual machine|",
          "5|S|Image size optimisation and layer caching in CI|",
          "5|S|Container registries and image tagging strategy|",
          "5|S|Kubernetes basics: pods, deployments, services, ingress|",
          "5|S|ConfigMaps, secrets, readiness and liveness probes, HPA, rolling updates|",
          "5|E|Helm, namespaces, resource limits and requests|",
        ],
      ],
      [
        "CI/CD and deployment",
        [
          "5|M|What a CI pipeline should do: lint, typecheck, test, build, deploy|Describe your ideal pipeline for a Node plus React repo.",
          "5|M|GitHub Actions: workflows, jobs, steps, caching, secrets, matrix builds|",
          "5|M|Deployment strategies: rolling, blue-green, canary|",
          "5|M|Feature flags and decoupling deploy from release|",
          "5|M|Environments, configuration, and the twelve-factor app|Why does configuration belong in the environment?",
          "5|M|Rollback strategy|Your deploy broke production. Walk through the next ten minutes.",
          "5|S|Database migrations in a CI/CD pipeline|",
          "5|S|Artifact versioning and reproducible builds|",
          "5|E|Infrastructure as code with Terraform|",
        ],
      ],
      [
        "Cloud and production operations",
        [
          "5|M|AWS core services and what each is for|EC2, S3, RDS, Lambda, API Gateway, CloudFront, Route53, IAM, VPC, SQS, SNS, ECS/Fargate, CloudWatch.",
          "5|M|IAM: users, roles, policies, least privilege|",
          "5|M|VPC, subnets, security groups vs NACLs|Why should your database never have a public IP?",
          "5|M|Nginx as a reverse proxy: SSL termination, static files, load balancing|",
          "5|M|Monitoring and alerting: what do you actually alert on?|Why is CPU a bad alert and latency a good one?",
          "5|M|Reading production logs to debug a live incident|",
          "5|S|Serverless: cold starts, execution limits, when Lambda fits|",
          "5|S|Autoscaling policies and capacity planning|",
          "5|S|Secrets management: Secrets Manager, Parameter Store, Vault|",
          "5|S|Incident response and blameless postmortems|",
          "5|S|Cost awareness: what actually runs up a cloud bill|",
          "5|E|Distributed tracing with OpenTelemetry|",
          "5|E|CDN configuration and cache invalidation at the edge|",
        ],
      ],
    ],
  },
  {
    number: "10",
    id: "test",
    name: "Testing, Quality & Debugging",
    blurb:
      "Almost every candidate says they write tests. Very few can explain what they would NOT test, or why their snapshot suite is worthless. That gap is easy to close and easy to notice.",
    groups: [
      [
        "Testing strategy",
        [
          "6|M|The testing pyramid and the testing trophy|Where do you get the most confidence per minute spent?",
          "6|M|Unit vs integration vs end-to-end — and what you would not test|",
          "6|M|Mocks vs stubs vs spies vs fakes|",
          "6|M|What makes a test valuable versus a test that just slows you down|Why are snapshot tests so often useless?",
          "6|M|Test-driven development — what it is and when you would actually use it|",
          "6|S|Flaky tests: causes and cures|",
          "6|S|Coverage as a metric and how it misleads|",
          "6|E|Contract testing between services|",
        ],
      ],
      [
        "Tools and practice",
        [
          "6|M|Jest or Vitest: matchers, mocks, spies, fake timers, setup and teardown|",
          "6|M|Testing async code and promises|",
          "6|M|React Testing Library: queries, user-event, testing behaviour not implementation|Why does RTL discourage testing state directly?",
          "6|M|Mocking network calls with MSW|",
          "6|M|Testing Express APIs with Supertest|",
          "6|M|Test database strategy: containers, transactions, fixtures, factories|How do you keep integration tests isolated and fast?",
          "6|S|End-to-end with Playwright or Cypress|",
          "6|S|Testing custom hooks|",
          "6|S|Load and performance testing|",
        ],
      ],
      [
        "Code quality and debugging",
        [
          "6|M|A systematic debugging method|Reproduce, isolate, hypothesise, verify. Talk through a real bug you fixed this way.",
          "6|M|Chrome DevTools and the Node inspector; breakpoints, watch, call stack|",
          "6|M|Debugging production: logs, traces, metrics, source maps|",
          "6|M|ESLint and Prettier; husky and lint-staged pre-commit hooks|",
          "6|M|What you look for in a code review|",
          "6|M|Code smells and the refactorings that fix them|Long function, large class, feature envy, primitive obsession, shotgun surgery.",
          "6|S|Cyclomatic complexity and when to split a function|",
          "6|S|Documentation: README quality, architecture decision records|",
          "6|S|Technical debt: how you track it and how you argue for paying it down|",
        ],
      ],
    ],
  },
  {
    number: "11",
    id: "rn",
    name: "React Native & Mobile",
    blurb:
      "Your differentiator. Very few backend-capable candidates can also ship a store-published app — but you will be asked about the bridge, list performance and the release process, and vague answers here read as CV padding.",
    groups: [
      [
        "Architecture and fundamentals",
        [
          "6|M|How React Native works: JS thread, native/UI thread, shadow thread|",
          "6|M|The old bridge vs the new architecture|JSI, Fabric, TurboModules, Codegen. Why was the bridge replaced?",
          "6|M|Hermes — what it changes for startup time and memory|",
          "6|M|React Native vs Flutter vs native|When would you tell a client NOT to use React Native?",
          "6|M|Expo vs bare workflow; EAS build|What forces you to eject, and what no longer does?",
          "6|M|Metro bundler and how RN differs from a web build|",
          "6|S|How native modules work; writing and autolinking one|",
        ],
      ],
      [
        "Building the app",
        [
          "6|M|Core components: View, Text, Image, ScrollView, FlatList, SectionList, TextInput, Pressable, Modal, SafeAreaView|",
          "6|M|FlatList performance|keyExtractor, getItemLayout, windowSize, initialNumToRender, removeClippedSubviews, memoised renderItem. Your list janks — diagnose it.",
          "6|M|ScrollView vs FlatList — and why using the wrong one kills the app|",
          "6|M|Styling: StyleSheet, flexbox differences from web, Dimensions, PixelRatio|Why is there no CSS, and what is the default flexDirection?",
          "6|M|Handling different screen sizes, notches, safe areas|",
          "6|M|Platform-specific code: Platform.select and .ios/.android files|",
          "6|M|React Navigation: stack, tab, drawer, nesting, params, auth flow|How do you structure a logged-in vs logged-out navigator?",
          "6|M|Deep linking and universal links|",
          "6|M|Storage: AsyncStorage, MMKV, SQLite, secure storage|Where do you keep an auth token on mobile?",
          "6|M|Permissions, camera, geolocation, file access|",
          "6|M|Push notifications: FCM and APNs, tokens, foreground vs background handling|",
          "6|S|Offline-first: queueing mutations, sync, conflict resolution|",
          "6|S|Animations: Animated vs Reanimated; Gesture Handler; running on the UI thread|Why does Reanimated feel smoother than the Animated API?",
          "6|S|Images: caching, resizing, FastImage, memory pressure|",
          "6|S|Forms and keyboard handling on mobile|",
        ],
      ],
      [
        "Shipping and debugging",
        [
          "6|M|Debugging: React Native DevTools, Flipper, Hermes profiling|",
          "6|M|App size optimisation: ProGuard/R8, Hermes bytecode, asset trimming|",
          "6|M|Release process: signing, keystores, provisioning profiles, TestFlight, Play Console|Walk through releasing v1.1 to both stores.",
          "6|M|Over-the-air updates: CodePush or EAS Update, and the store rules that limit them|What can you ship OTA and what legally cannot go OTA?",
          "6|M|Crash reporting with Sentry or Crashlytics; reading a native stack trace|",
          "6|S|Environment configuration and build variants/flavours|",
          "6|S|CI for mobile: Fastlane, EAS, automated builds|",
          "6|S|Analytics and funnel tracking in an app|",
          "6|E|Upgrading React Native versions without losing a week|",
        ],
      ],
    ],
  },
  {
    number: "12",
    id: "behav",
    name: "Behavioural & Communication",
    blurb:
      "Strong engineers lose offers here more often than they lose them on DSA. Every one of these needs a rehearsed, specific, 90-second answer with real numbers — not a story you invent in the room.",
    groups: [
      [
        "The answers you must have ready",
        [
          "1|M|Tell me about yourself|90 seconds: where you are now, what you have built, why you are looking, what you want next. Write it, then rehearse it until it is not a recitation.",
          "1|M|Walk me through your current project|Architecture, your specific contribution, the hardest decision, real numbers.",
          "6|M|Why are you leaving your current company?|Honest, forward-looking, never bitter. Prepare the exact wording.",
          "6|M|Why this company / why this role?|Requires actual research. Generic answers are visibly generic.",
          "6|M|Where do you see yourself in three years?|",
          "6|M|Your greatest strength and a real weakness|A weakness you are genuinely working on, with evidence.",
          "6|M|Why should we hire you over someone from a product company?|Prepare this one verbatim. It will come.",
          "6|M|Questions you ask the interviewer|Team structure, on-call, how tech debt is handled, what success looks like at 6 months, why the role is open.",
          "6|S|Explain a technical concept to a non-technical stakeholder|",
        ],
      ],
      [
        "STAR stories to prepare (two each)",
        [
          "6|M|A hard bug you debugged|Situation, what you tried, how you isolated it, the fix, what you changed afterwards.",
          "6|M|A time you improved performance|With before and after numbers. This is the highest-value story you own.",
          "6|M|A conflict with a teammate or manager|",
          "6|M|A time you missed a deadline or shipped something broken|What you owned, what you changed structurally.",
          "6|M|A time you disagreed with a technical decision|Did you commit anyway? How?",
          "6|M|A time you took ownership beyond your role|",
          "6|M|Something complex you learned quickly under pressure|",
          "6|M|Feedback you received and acted on|",
          "6|S|A time you mentored or unblocked someone|",
          "6|S|A tradeoff you made deliberately — and would you make it again|",
          "6|S|A time you pushed back on scope or requirements|",
          "6|S|How you handled a production incident|",
        ],
      ],
      [
        "Interview craft",
        [
          "2|M|Thinking out loud while coding|Silence reads as being stuck. Practise narrating.",
          "2|M|Asking clarifying questions before you start|In every round, always. It is graded.",
          "6|M|Handling a question you do not know|Say what you do know, reason toward it, never bluff. Interviewers respect this and punish bluffing.",
          "6|M|Recovering after a bad round|",
          "6|M|Mock interviews: peers, Pramp, or record yourself|Do at least six before your first real interview.",
          "6|M|Salary negotiation|Know your number, avoid disclosing first, negotiate total comp, use competing offers. Never accept on the call.",
          "6|S|Discussing notice period, offer timelines and juggling processes|",
          "6|S|Post-interview follow-up|",
          "6|S|Remote interview logistics: setup, connection, screen sharing, editor ready|",
        ],
      ],
    ],
  },
  {
    number: "13",
    id: "pos",
    name: "Resume, Portfolio & Job Strategy",
    blurb:
      "Do this in week one, not week six. Everything else on this page is worthless if your CV does not get opened — and the pipeline takes weeks to warm up.",
    groups: [
      [
        "Resume",
        [
          "1|M|One page, reverse chronological, no photo, no skill bars|",
          "1|M|Impact-first bullets: action, technology, measurable result|Rewrite every bullet that begins with 'Responsible for'.",
          "1|M|Quantify everything you honestly can|Latency, users, requests, cost, time saved, bugs reduced, build time.",
          "1|M|Only list skills you can survive 20 minutes of questioning on|Anything on your resume is fair game. Cut the rest.",
          "1|M|ATS-friendly formatting; keywords pulled from real job descriptions|",
          "1|M|Frame service-based work as breadth|Multiple clients, domains, end-to-end ownership, shipping under real deadlines.",
          "1|S|A short professional summary tuned per role type|",
          "1|S|Get it reviewed by two people who have hired engineers|",
        ],
      ],
      [
        "Portfolio and public presence",
        [
          "1|M|Pin three strong GitHub repos with real READMEs|Problem, architecture diagram, decisions, setup, screenshots.",
          "1|M|One flagship project that shows depth|Auth, real data modelling, caching, background jobs, tests, CI, deployed and reachable.",
          "1|M|LinkedIn: headline, About section, experience mirrored from the resume, open-to-work signals|",
          "2|S|Clean up commit history and remove dead repos from the top of your profile|",
          "2|S|Write two short technical posts about something you actually debugged|Cheap credibility, and it gives interviewers something to ask about.",
          "6|E|A personal site or portfolio page|",
        ],
      ],
      [
        "Job search operations",
        [
          "2|M|Start applying at the end of week 2 — do not wait until you feel ready|Early interviews are diagnostics. They will tell you what is actually weak.",
          "2|M|Referrals: how to ask, and a cold outreach template that is not spam|A referral converts several times better than a portal application.",
          "2|M|Track every application in one sheet|Company, role, source, date, stage, contact, next action.",
          "2|M|Keep 15 to 20 live pipelines so no single outcome matters|",
          "2|M|Research each company before the first round|Product, stage, tech stack, recent news, who is interviewing you.",
          "3|M|Take-home assignments: scope, timebox, README, tests|Do not gold-plate. Do explain your tradeoffs in writing.",
          "6|M|Try to bunch onsites so offers land in the same window|That is what creates negotiating leverage.",
          "6|S|Know your target number and your walk-away number before any call|",
        ],
      ],
    ],
  },
];

function parseItem(encoded: string): SyllabusItem {
  const [week, priority, title, question = ""] = encoded.split("|");
  return {
    week: Number(week),
    priority: priority as Priority,
    title,
    question: question.trim(),
  };
}

export const syllabus: SyllabusTrack[] = raw.map((track) => ({
  number: track.number,
  id: track.id,
  name: track.name,
  blurb: track.blurb,
  groups: track.groups.map(([name, items]) => ({
    name,
    items: items.map(parseItem),
  })),
}));

export const allItems: SyllabusItem[] = syllabus.flatMap((track) =>
  track.groups.flatMap((group) => group.items),
);

export const totalTopics = allItems.length;
export const coreTopics = allItems.filter((item) => item.priority === "M").length;

export function trackTopicCount(track: SyllabusTrack): number {
  return track.groups.reduce((sum, group) => sum + group.items.length, 0);
}

export function topicsByWeek(week: number): number {
  return allItems.filter((item) => item.week === week).length;
}
